DROP DATABASE IF EXISTS DBGoP ;
CREATE DATABASE DBGoP ;
USE DBGoP ;

CREATE TABLE Rarity (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(3) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Attribute (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Race (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Gift (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Ingredients (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    location VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Food (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    ingredient_1 INTEGER,
    ingredient_2 INTEGER,
    ingredient_3 INTEGER,
    effect VARCHAR(50) NOT NULL,
    location VARCHAR(50),
    PRIMARY KEY (id),
    FOREIGN KEY (ingredient_1) REFERENCES Ingredients(id),
    FOREIGN KEY (ingredient_2) REFERENCES Ingredients(id),
    FOREIGN KEY (ingredient_3) REFERENCES Ingredients(id)
);

CREATE TABLE Equipment (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    set_number INTEGER NOT NULL,
    bonus VARCHAR(100) NOT NULL,
    location VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);