DROP DATABASE IF EXISTS DBGoP ;
CREATE DATABASE DBGoP ;
USE DBGoP ;

CREATE TABLE Rarity (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(3) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Attribute (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Race (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Gift (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Food (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Equipment (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    set_number INTEGER NOT NULL,
    bonus VARCHAR(100) NOT NULL,
    location VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);